In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
# file_name = "training.json"
# file_output = "training_stats.csv"
# data_name = "training"

In [3]:
# file_name = "dev.json"
# file_output = "dev_stats.csv"
# data_name = "dev"

In [4]:
file_name = "test.json"
file_output = "test_stats.csv"
data_name = "test"

In [5]:
f = open(file_name)
data = json.load(f)
f.close()

In [6]:
arr = data['data']
N = len(arr)

In [7]:
final_dict = {}

#### NUmber of texts

In [8]:
text_set = set()
for element in arr:
    text_set.add(element["context"])

n_texts = len(text_set)
final_dict["# of texts"] = n_texts
n_texts

48

#### Count Questions

In [9]:
n_questions = len(arr)
final_dict["# of MCQs"] = n_questions
n_questions

50

#### One answer per choice

In [10]:
n_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_ans = 0  
    for choice in choices:
        if choice["type"] == "correct answer":
            n_ans +=1
    n_answers[idx] = n_ans

In [11]:
n_answers

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
for element in n_answers:
    assert element == 1

#### Number of distractors

In [13]:
n_distractors = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_dist = 0 
    for choice in choices:
        if choice["type"] == "distractor":
            n_dist +=1
    assert n_dist < 5
    n_distractors[idx] = n_dist

In [14]:
n_distractors

array([3., 3., 3., 3., 3., 4., 2., 4., 2., 4., 4., 4., 4., 3., 3., 3., 4.,
       3., 4., 3., 3., 3., 4., 2., 4., 2., 4., 4., 3., 2., 4., 4., 4., 4.,
       3., 2., 4., 2., 2., 2., 3., 3., 3., 4., 3., 4., 2., 3., 3., 4.])

In [37]:
np.unique(n_distractors, return_counts=True)

(array([2., 3., 4.]), array([10, 20, 20]))

In [15]:
n_dist_mean = np.mean(n_distractors)
n_dist_std = np.std(n_distractors)

In [16]:
print(n_dist_mean)
print(n_dist_std)
final_dict["# of D"] = f"{n_dist_mean:0.2f} +- {n_dist_std:0.2f}"
final_dict["# of D"]

3.2
0.7483314773547883


'3.20 +- 0.75'

### Length of texts

In [17]:
def count_words(_string):
    arr = _string.split(" ")
    return len(arr)

In [18]:
len_texts = np.zeros(N)
for idx, element in enumerate(arr):
    context = element["context"]
    len_texts[idx] = count_words(context)

len_texts

array([133., 118., 160., 197., 136., 136., 119., 192., 210.,  93., 182.,
       222., 139., 203., 161., 184., 108., 213., 106., 149., 194., 146.,
       129., 178., 264., 117., 101.,  76., 193., 195., 256.,  82., 184.,
       114., 200., 145., 113., 101., 101., 153., 125., 171., 108., 449.,
       212., 127., 145., 150., 121.,  98.])

In [19]:
max_length_text = np.max(len_texts)
max_length_text

449.0

In [20]:
text_mean = np.mean(len_texts)
text_std = np.std(len_texts)
print(text_mean)
print(text_std)

158.18
60.75053580010633


In [21]:
final_dict["Len(Text)"] = f"{text_mean:0.2f} +- {text_std:0.2f}"
final_dict["Max(Text)"] = max_length_text
final_dict["Len(Text)"]

'158.18 +- 60.75'

#### Length of answers

In [22]:
len_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            len_answers[idx] = count_words(ans)

len_answers

array([ 2.,  1., 10.,  8.,  7.,  2.,  3.,  8.,  2.,  1.,  1.,  5.,  3.,
        9.,  4.,  2.,  3.,  7.,  2., 11.,  3.,  1.,  1.,  1., 12.,  1.,
        4.,  1.,  2.,  1., 12.,  1.,  4.,  1.,  1.,  2.,  4.,  1., 13.,
       15.,  1.,  5.,  9.,  9., 11.,  5., 19.,  3.,  2.,  2.])

In [23]:
max_length_ans = np.max(len_answers)
max_length_ans

19.0

In [24]:
ans_mean = np.mean(len_answers)
ans_std = np.std(len_answers)
print(ans_mean)
print(ans_std)

4.76
4.370629245314683


In [25]:
final_dict["Len(A)"] = f"{ans_mean:0.2f} +- {ans_std:0.2f}"
final_dict["Max(A)"] = max_length_ans
final_dict["Len(A)"]

'4.76 +- 4.37'

#### Length of distractors

In [26]:
len_distractors = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "distractor":
            dist = choice["text"]
            len_distractors.append(count_words(dist))

len_distractors = np.array(len_distractors)
len_distractors

array([ 3,  1,  3,  7,  3,  3,  6, 17,  4, 10, 10, 14, 10,  7,  7,  3,  3,
        2,  5,  2,  3,  5,  9,  6,  7,  3,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  7,  7,  9,  8,  5,  4,  3,  3,  9, 14, 15,  2,  2,  2,  2,  1,
        1,  1,  1,  4,  3,  4,  4,  5,  3,  5,  3,  3,  3,  4,  2,  4,  4,
        4,  1,  1,  2,  4,  3,  2,  1,  1,  1, 15,  7,  8,  6,  2,  1,  3,
        3,  7,  7,  1,  1,  1,  1,  3,  3,  2,  2,  1,  3,  4,  4,  6,  1,
        1,  1,  1,  2,  2,  5,  3,  1,  1,  1,  1,  1,  1,  1,  2,  2,  1,
        1,  3,  2,  1,  1, 10, 10, 15,  6,  1,  1,  1,  3,  4,  7,  5,  4,
        7,  6, 11,  6,  6,  8,  7, 10,  4,  5,  4,  4, 11, 13,  3,  4,  7,
        2,  1,  2,  2,  2,  2,  2])

In [27]:
max_length_dist = np.max(len_distractors)
max_length_dist

17

In [28]:
dist_mean = np.mean(len_distractors)
dist_std = np.std(len_distractors)
print(dist_mean)
print(dist_std)

4.075
3.463289621155008


In [29]:
final_dict["Len(D)"] = f"{dist_mean:0.2f} +- {dist_std:0.2f}"
final_dict["Max(D)"] = max_length_dist
final_dict["Len(D)"]

'4.08 +- 3.46'

### Diference ans and Dist

In [30]:
len_differences = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    dists_length = []
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            ans_length = count_words(ans)
        if choice["type"] == "distractor":
            dist = choice["text"]
            dists_length.append(count_words(dist))
    
    arr_diff = np.array([abs(ans_length-x) for x in dists_length])
    diff = np.mean(arr_diff)
    len_differences.append(diff)

len_differences = np.array(len_differences)
len_differences

array([1.        , 3.33333333, 5.66666667, 3.33333333, 1.        ,
       1.25      , 0.5       , 1.75      , 1.        , 0.        ,
       0.        , 2.75      , 0.75      , 3.66666667, 2.        ,
       0.66666667, 1.25      , 2.66666667, 1.5       , 8.        ,
       1.        , 0.33333333, 1.5       , 0.        , 4.5       ,
       0.5       , 2.        , 0.        , 0.66666667, 0.5       ,
       7.75      , 0.        , 1.5       , 0.        , 0.        ,
       0.        , 2.25      , 0.        , 3.        , 4.5       ,
       0.        , 1.66666667, 3.66666667, 2.75      , 2.66666667,
       0.75      , 7.        , 1.66666667, 0.33333333, 0.        ])

In [31]:
max_length_diff = np.max(len_differences)
max_length_diff

8.0

In [32]:
diff_mean = np.mean(len_differences)
diff_std = np.std(len_differences)
print(diff_mean)
print(diff_std)

1.8516666666666666
2.0012003342438702


In [33]:
final_dict["|Len(A) - Len(D)|"] = f"{diff_mean:0.2f} +- {diff_std:0.2f}"
final_dict["Max(|Len(A) - Len(D)|)"] = max_length_diff
final_dict["|Len(A) - Len(D)|"]

'1.85 +- 2.00'

# Final CSV

In [34]:
df = pd.Series(final_dict, name=data_name)
df

# of texts                             48
# of MCQs                              50
# of D                       3.20 +- 0.75
Len(Text)                 158.18 +- 60.75
Max(Text)                           449.0
Len(A)                       4.76 +- 4.37
Max(A)                               19.0
Len(D)                       4.08 +- 3.46
Max(D)                                 17
|Len(A) - Len(D)|            1.85 +- 2.00
Max(|Len(A) - Len(D)|)                8.0
Name: test, dtype: object

In [35]:
df.to_csv(file_output)