In [71]:
import numpy as np
import pandas as pd
import json

In [72]:
file_name = "training.json"
file_output = "training_stats.csv"
data_name = "training"

In [73]:
# file_name = "dev.json"
# file_output = "dev_stats.csv"
# data_name = "dev"

In [74]:
# file_name = "test.json"
# file_output = "test_stats.csv"
# data_name = "test"

In [75]:
f = open(file_name)
data = json.load(f)
f.close()

In [76]:
arr = data['data']
N = len(arr)

In [77]:
final_dict = {}

#### NUmber of texts

In [78]:
text_set = set()
for element in arr:
    text_set.add(element["context"])

n_texts = len(text_set)
final_dict["# of texts"] = n_texts
n_texts

810

#### Count Questions

In [79]:
n_questions = len(arr)
final_dict["# of MCQs"] = n_questions
n_questions

835

#### One answer per choice

In [80]:
n_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_ans = 0  
    for choice in choices:
        if choice["type"] == "correct answer":
            n_ans +=1
    n_answers[idx] = n_ans

In [81]:
n_answers

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [82]:
for element in n_answers:
    assert element == 1

#### Number of distractors

In [83]:
n_distractors = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_dist = 0 
    for choice in choices:
        if choice["type"] == "distractor":
            n_dist +=1
    assert n_dist < 5
    n_distractors[idx] = n_dist

In [84]:
n_distractors

array([2., 2., 4., 4., 2., 3., 3., 4., 4., 3., 2., 2., 2., 2., 2., 4., 4.,
       4., 3., 4., 4., 3., 3., 4., 2., 3., 4., 3., 3., 2., 4., 4., 3., 4.,
       3., 2., 2., 4., 3., 4., 3., 4., 3., 3., 4., 4., 4., 3., 3., 4., 3.,
       3., 4., 4., 3., 3., 4., 4., 4., 4., 3., 2., 2., 3., 3., 3., 3., 4.,
       4., 3., 2., 3., 4., 2., 3., 3., 4., 3., 3., 4., 4., 4., 2., 3., 4.,
       4., 3., 3., 3., 3., 2., 4., 3., 4., 3., 3., 3., 2., 4., 3., 4., 3.,
       3., 4., 4., 3., 2., 3., 3., 4., 4., 3., 2., 2., 4., 4., 2., 4., 2.,
       3., 3., 4., 3., 3., 2., 3., 3., 4., 3., 3., 3., 3., 2., 3., 4., 3.,
       3., 2., 2., 3., 4., 2., 4., 2., 3., 3., 4., 2., 2., 3., 4., 4., 3.,
       4., 3., 4., 2., 4., 3., 4., 3., 3., 2., 3., 3., 4., 2., 4., 4., 2.,
       3., 4., 3., 4., 3., 4., 3., 4., 3., 3., 4., 3., 3., 2., 3., 3., 3.,
       4., 4., 3., 4., 4., 2., 3., 2., 3., 3., 4., 3., 4., 3., 3., 3., 3.,
       3., 2., 3., 2., 3., 3., 4., 4., 4., 4., 3., 3., 2., 4., 4., 2., 3.,
       4., 4., 4., 3., 3.

In [85]:
n_dist_mean = np.mean(n_distractors)
n_dist_std = np.std(n_distractors)

In [86]:
print(n_dist_mean)
print(n_dist_std)
final_dict["# of D"] = f"{n_dist_mean:0.2f} +- {n_dist_std:0.2f}"
final_dict["# of D"]

3.1592814371257485
0.7372188950618791


'3.16 +- 0.74'

### Length of texts

In [87]:
def count_words(_string):
    arr = _string.split(" ")
    return len(arr)

In [88]:
len_texts = np.zeros(N)
for idx, element in enumerate(arr):
    context = element["context"]
    len_texts[idx] = count_words(context)

len_texts

array([ 94., 171., 102., 159., 154., 109., 237., 211., 302., 182.,  90.,
       112., 152., 247., 105., 123.,  48., 140., 271., 271., 105., 195.,
       170., 124., 165., 162., 169., 106., 150.,  90., 123., 197., 127.,
       159.,  92., 132.,  61., 206., 136., 114., 174., 219., 177., 108.,
       218., 218., 149., 158., 102., 213., 152., 247., 158., 123.,  82.,
       107., 165., 178., 122., 157., 172.,  79.,  96., 186., 176., 129.,
       182., 200., 127., 127.,  92., 138., 224., 165., 122.,  87., 211.,
       122.,  89., 112., 142., 175.,  93.,  92., 146., 235., 154., 216.,
       204., 179., 130., 102., 268., 268., 116., 116., 159., 113.,  87.,
       185., 185., 185., 106., 187., 123., 114.,  90., 124., 120., 157.,
       215., 118., 124., 139., 134., 181., 119.,  84., 126., 248., 127.,
       237., 167., 141., 120., 150., 170., 143., 182., 136., 244., 195.,
       120., 157., 111., 174., 200., 119., 169., 134., 305., 146., 283.,
        92., 194., 453., 213., 142.,  93.,  93., 24

In [89]:
max_length_text = np.max(len_texts)
max_length_text

453.0

In [90]:
text_mean = np.mean(len_texts)
text_std = np.std(len_texts)
print(text_mean)
print(text_std)

158.2059880239521
54.85740437208974


In [91]:
final_dict["Len(Text)"] = f"{text_mean:0.2f} +- {text_std:0.2f}"
final_dict["Max(Text)"] = max_length_text
final_dict["Len(Text)"]

'158.21 +- 54.86'

#### Length of answers

In [92]:
len_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            len_answers[idx] = count_words(ans)

len_answers

array([ 2.,  1.,  1.,  2.,  1.,  1., 19., 13.,  2.,  1.,  3.,  1.,  1.,
        8.,  1.,  2.,  3.,  1.,  1., 21.,  2.,  2.,  8.,  1.,  6.,  5.,
        2.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  2., 14.,  1.,  3.,  1.,
        2., 13., 10.,  1.,  3.,  1.,  1.,  2.,  1.,  2.,  1.,  4.,  4.,
        1.,  2.,  1.,  4.,  1.,  4.,  1., 19.,  3.,  2.,  2., 10., 15.,
        1., 10.,  4.,  2.,  1.,  1.,  1.,  2., 17.,  4., 16., 15.,  4.,
        1.,  1.,  2.,  3.,  2.,  2.,  4.,  4.,  1.,  2.,  9.,  8., 10.,
        1., 14.,  1.,  6.,  3.,  6.,  1.,  1.,  2.,  2.,  5.,  4.,  1.,
        1.,  2.,  2.,  1.,  1.,  1., 13.,  9.,  1.,  1.,  3.,  2.,  3.,
        1.,  4.,  8.,  2.,  2.,  5.,  9.,  6.,  1.,  3.,  2., 19.,  2.,
        1., 16.,  1.,  1.,  2., 13., 11.,  2.,  1.,  1.,  8., 18.,  1.,
        1.,  8., 15., 21.,  4.,  2., 13.,  6.,  4.,  1.,  4.,  3.,  1.,
        3.,  3.,  5.,  3.,  5., 13., 10.,  2.,  7.,  2., 10.,  1.,  1.,
        1.,  1.,  1.,  2.,  3., 16.,  1.,  4.,  1.,  2.,  1.,  2

In [93]:
max_length_ans = np.max(len_answers)
max_length_ans

26.0

In [94]:
ans_mean = np.mean(len_answers)
ans_std = np.std(len_answers)
print(ans_mean)
print(ans_std)

4.355688622754491
4.49075703832836


In [95]:
final_dict["Len(A)"] = f"{ans_mean:0.2f} +- {ans_std:0.2f}"
final_dict["Max(A)"] = max_length_ans
final_dict["Len(A)"]

'4.36 +- 4.49'

#### Length of distractors

In [96]:
len_distractors = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "distractor":
            dist = choice["text"]
            len_distractors.append(count_words(dist))

len_distractors = np.array(len_distractors)
len_distractors

array([1, 1, 1, ..., 1, 2, 1])

In [97]:
max_length_dist = np.max(len_distractors)
max_length_dist

43

In [98]:
dist_mean = np.mean(len_distractors)
dist_std = np.std(len_distractors)
print(dist_mean)
print(dist_std)

4.59325246398787
4.969373979282124


In [99]:
final_dict["Len(D)"] = f"{dist_mean:0.2f} +- {dist_std:0.2f}"
final_dict["Max(D)"] = max_length_dist
final_dict["Len(D)"]

'4.59 +- 4.97'

### Diference ans and Dist

In [100]:
len_differences = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    dists_length = []
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            ans_length = count_words(ans)
        if choice["type"] == "distractor":
            dist = choice["text"]
            dists_length.append(count_words(dist))
    
    arr_diff = np.array([abs(ans_length-x) for x in dists_length])
    diff = np.mean(arr_diff)
    len_differences.append(diff)

len_differences = np.array(len_differences)
len_differences

array([ 1.        ,  0.        ,  2.5       ,  1.        ,  0.        ,
        1.        ,  8.        ,  5.25      ,  0.75      ,  0.        ,
        0.        ,  0.        ,  0.        ,  3.5       ,  0.        ,
        1.        ,  1.25      ,  0.        ,  0.        ,  6.5       ,
        0.5       ,  1.        ,  9.        ,  0.        ,  0.5       ,
        8.33333333,  2.75      ,  0.66666667,  1.        ,  0.        ,
        1.75      ,  1.        ,  0.        ,  2.75      ,  1.66666667,
        2.        ,  0.        ,  0.75      ,  0.        ,  0.75      ,
        7.        ,  3.25      ,  0.        ,  1.33333333,  0.25      ,
        0.5       ,  0.75      ,  0.        ,  1.        ,  0.        ,
        1.33333333,  1.        ,  1.25      ,  0.75      ,  0.        ,
        2.        ,  0.        ,  2.        ,  0.75      ,  5.25      ,
        1.        ,  1.5       ,  0.        ,  6.33333333,  3.        ,
        0.        ,  2.33333333,  4.        ,  0.25      ,  0.33

In [101]:
max_length_diff = np.max(len_differences)
max_length_diff

16.666666666666668

In [102]:
diff_mean = np.mean(len_differences)
diff_std = np.std(len_differences)
print(diff_mean)
print(diff_std)

1.6901197604790419
2.284262421295633


In [103]:
final_dict["|Len(A) - Len(D)|"] = f"{diff_mean:0.2f} +- {diff_std:0.2f}"
final_dict["Max(|Len(A) - Len(D)|)"] = max_length_diff
final_dict["|Len(A) - Len(D)|"]

'1.69 +- 2.28'

# Final CSV

In [104]:
df = pd.Series(final_dict, name=data_name)
df

# of texts                            810
# of MCQs                             835
# of D                       3.16 +- 0.74
Len(Text)                 158.21 +- 54.86
Max(Text)                           453.0
Len(A)                       4.36 +- 4.49
Max(A)                               26.0
Len(D)                       4.59 +- 4.97
Max(D)                                 43
|Len(A) - Len(D)|            1.69 +- 2.28
Max(|Len(A) - Len(D)|)          16.666667
Name: training, dtype: object

In [105]:
df.to_csv(file_output)