In [334]:
import numpy as np
import pandas as pd
import json

In [335]:
# file_name = "train.json"
# file_output = "train_stats.csv"

In [336]:
file_name = "dev.json"
file_output = "dev_stats.csv"

In [337]:
# file_name = "test.json"
# file_output = "test_stats.csv"

In [338]:
f = open(file_name)
data = json.load(f)
f.close()

In [339]:
arr = data['data']
N = len(arr)

In [340]:
final_dict = {}

#### NUmber of texts

In [341]:
text_set = set()
for element in arr:
    text_set.add(element["context"])

n_texts = len(text_set)
final_dict["# of texts"] = n_texts
n_texts

95

#### Count Questions

In [342]:
n_questions = len(arr)
final_dict["# of MCQs"] = n_questions
n_questions

95

#### One answer per choice

In [343]:
n_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_ans = 0  
    for choice in choices:
        if choice["type"] == "correct answer":
            n_ans +=1
    n_answers[idx] = n_ans

In [344]:
n_answers

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [345]:
for element in n_answers:
    assert element == 1

#### Number of distractors

In [346]:
n_distractors = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_dist = 0 
    for choice in choices:
        if choice["type"] == "distractor":
            n_dist +=1
    assert n_dist < 5
    n_distractors[idx] = n_dist

In [347]:
n_distractors

array([4., 3., 2., 3., 3., 4., 3., 4., 4., 3., 4., 4., 3., 4., 2., 4., 4.,
       2., 4., 4., 2., 2., 3., 3., 4., 4., 4., 3., 3., 3., 3., 3., 3., 4.,
       3., 2., 4., 3., 4., 4., 4., 4., 4., 2., 3., 3., 3., 4., 3., 2., 3.,
       3., 4., 3., 3., 3., 4., 3., 4., 4., 4., 4., 3., 2., 3., 3., 2., 3.,
       4., 3., 4., 3., 4., 3., 2., 3., 4., 2., 3., 3., 3., 4., 3., 3., 3.,
       3., 4., 3., 4., 3., 3., 2., 4., 3., 2.])

In [348]:
n_dist_mean = np.mean(n_distractors)
n_dist_std = np.std(n_distractors)

In [349]:
print(n_dist_mean)
print(n_dist_std)
final_dict["# of D"] = f"{n_dist_mean:0.2f} +- {n_dist_std:0.2f}"
final_dict["# of D"]

3.231578947368421
0.6875223491708603


'3.23 +- 0.69'

### Length of texts

In [350]:
def count_words(_string):
    arr = _string.split(" ")
    return len(arr)

In [351]:
len_texts = np.zeros(N)
for idx, element in enumerate(arr):
    context = element["context"]
    len_texts[idx] = count_words(context)

len_texts

array([109., 211., 103., 126., 101., 226., 194., 155., 144., 174.,  95.,
       106., 103., 178., 151., 195., 144., 159., 219., 169., 146., 110.,
       203., 114., 248., 144., 211., 155., 108., 222., 140., 157., 174.,
       157., 141., 141., 225., 203., 236., 208., 125., 216., 147., 143.,
        95., 113., 185.,  56., 201., 202., 102., 116., 217., 247., 110.,
        86., 120., 137., 169., 117., 162., 134., 117.,  92.,  94., 122.,
       199.,  75., 170., 129., 297., 169., 261., 118., 218., 173., 162.,
       215.,  78., 222., 173., 121., 209., 147., 134., 113., 197.,  81.,
       174., 195., 152., 113., 152., 279., 197.])

In [352]:
max_length_text = np.max(len_texts)
max_length_text

297.0

In [353]:
text_mean = np.mean(len_texts)
text_std = np.std(len_texts)
print(text_mean)
print(text_std)

158.45263157894738
49.52973979998017


In [354]:
final_dict["Len(Text)"] = f"{text_mean:0.2f} +- {text_std:0.2f}"
final_dict["Max(Text)"] = max_length_text
final_dict["Len(Text)"]

'158.45 +- 49.53'

#### Length of answers

In [355]:
len_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            len_answers[idx] = count_words(ans)

len_answers

array([ 2., 14.,  2., 12.,  1.,  2., 16.,  6.,  1.,  3.,  3.,  1., 14.,
        2.,  7.,  9.,  2.,  1.,  1.,  4.,  1.,  5.,  8.,  1.,  2.,  1.,
       10.,  2., 13., 15.,  2., 10.,  1.,  2.,  3., 11.,  2., 17.,  7.,
        5.,  1.,  4.,  8.,  7.,  2.,  2.,  2.,  3.,  1.,  4.,  4., 10.,
        6., 22.,  7.,  1.,  6., 11.,  2.,  6.,  3.,  1.,  9.,  1.,  2.,
        2.,  2.,  6., 11.,  1., 10.,  8.,  8.,  5., 14.,  5.,  1.,  1.,
        5.,  6.,  4.,  2., 11.,  3.,  6.,  2., 12.,  1.,  3.,  2.,  9.,
        1.,  2., 15., 14.])

In [356]:
max_length_ans = np.max(len_answers)
max_length_ans

22.0

In [357]:
ans_mean = np.mean(len_answers)
ans_std = np.std(len_answers)
print(ans_mean)
print(ans_std)

5.4526315789473685
4.698865307715832


In [358]:
final_dict["Len(A)"] = f"{ans_mean:0.2f} +- {ans_std:0.2f}"
final_dict["Max(A)"] = max_length_ans
final_dict["Len(A)"]

'5.45 +- 4.70'

#### Length of distractors

In [359]:
len_distractors = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "distractor":
            dist = choice["text"]
            len_distractors.append(count_words(dist))

len_distractors = np.array(len_distractors)
len_distractors

array([ 2,  2,  2,  2, 12, 23,  8,  3,  2,  8,  5, 12,  1,  1,  1,  1,  1,
        2,  1, 16, 24, 18,  4,  9,  4,  8,  1,  1,  1,  1,  1,  1,  2,  7,
       13,  7,  3,  1,  1,  1,  1,  7,  4,  5,  3,  2,  2,  3, 10, 10, 12,
       22, 13, 17,  3,  2,  2,  2,  1,  2,  1,  2,  1,  1,  3,  2,  3,  5,
        1,  1,  7, 11,  9,  8,  8,  1,  1,  1,  4,  2,  2,  2,  1,  1,  1,
        1, 19, 18, 13, 21,  2,  2,  2, 10,  6,  8, 11, 14, 25,  2,  4,  2,
        7, 12,  7,  1,  1,  1,  3,  2,  3,  2,  2,  2,  2, 10, 24,  2,  2,
        2,  2,  6, 13,  7, 22, 12, 19, 11,  5,  5,  5,  3,  1,  1,  1,  1,
        2,  6,  5,  4,  2,  8,  5,  5,  8,  9,  2,  2,  1,  2,  6,  5,  4,
        2,  2,  1,  3,  2,  3,  1,  1,  1,  4,  4,  2,  2,  3,  8,  6, 11,
        3,  7,  6,  5, 16,  7, 12,  7,  7,  5,  1,  1,  1,  6,  6,  6,  6,
       23, 11,  7,  3,  2,  3,  2,  6,  6,  6,  6,  4,  4,  3,  3,  1,  2,
        3,  3,  7,  7, 13,  1,  1,  2,  2,  2,  4,  2,  2,  3,  4,  6,  6,
        6,  8, 17, 13, 12

In [360]:
max_length_dist = np.max(len_distractors)
max_length_dist

32

In [361]:
dist_mean = np.mean(len_distractors)
dist_std = np.std(len_distractors)
print(dist_mean)
print(dist_std)

5.615635179153094
5.529501851010265


In [362]:
final_dict["Len(D)"] = f"{dist_mean:0.2f} +- {dist_std:0.2f}"
final_dict["Max(D)"] = max_length_dist
final_dict["Len(D)"]

'5.62 +- 5.53'

### Diference ans and Dist

In [363]:
len_differences = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    dists_length = []
    for choice in choices:
        if choice["type"] == "correct answer":
            ans = choice["text"]
            ans_length = count_words(ans)
        if choice["type"] == "distractor":
            dist = choice["text"]
            dists_length.append(count_words(dist))
    
    arr_diff = np.array([abs(ans_length-x) for x in dists_length])
    diff = np.mean(arr_diff)
    len_differences.append(diff)

len_differences = np.array(len_differences)
len_differences

array([ 0.        ,  5.66666667,  0.5       ,  3.66666667,  0.        ,
        0.75      ,  3.33333333,  2.25      ,  0.        ,  1.66666667,
        4.5       ,  0.        ,  8.66666667,  0.5       ,  3.        ,
        7.        ,  0.25      ,  0.5       ,  0.25      ,  1.25      ,
        0.        ,  4.        ,  0.33333333,  0.        ,  0.5       ,
        0.        ,  7.75      ,  0.        ,  5.        ,  5.        ,
        0.66666667,  2.66666667,  0.        ,  0.5       ,  1.        ,
        7.        ,  0.        ,  8.33333333,  9.        ,  0.5       ,
        0.        ,  1.25      ,  3.        ,  1.5       ,  0.33333333,
        2.33333333,  0.66666667,  0.75      ,  0.        ,  0.        ,
        1.66666667,  2.33333333,  1.25      , 10.33333333,  0.66666667,
        0.        ,  0.        ,  5.33333333,  0.5       ,  0.        ,
        0.5       ,  1.25      ,  2.66666667,  0.        ,  0.        ,
        0.66666667,  1.5       ,  0.        ,  3.        ,  0.  

In [364]:
max_length_diff = np.max(len_differences)
max_length_diff

10.333333333333334

In [365]:
diff_mean = np.mean(len_differences)
diff_std = np.std(len_differences)
print(diff_mean)
print(diff_std)

2.0807017543859647
2.515607789079302


In [366]:
final_dict["|Len(A) - Len(D)|"] = f"{diff_mean:0.2f} +- {diff_std:0.2f}"
final_dict["Max(|Len(A) - Len(D)|)"] = max_length_diff
final_dict["|Len(A) - Len(D)|"]

'2.08 +- 2.52'

# Final CSV

In [367]:
df = pd.Series(final_dict)
df

# of texts                             95
# of MCQs                              95
# of D                       3.23 +- 0.69
Len(Text)                 158.45 +- 49.53
Max(Text)                           297.0
Len(A)                       5.45 +- 4.70
Max(A)                               22.0
Len(D)                       5.62 +- 5.53
Max(D)                                 32
|Len(A) - Len(D)|            2.08 +- 2.52
Max(|Len(A) - Len(D)|)          10.333333
dtype: object